IF (NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES 
                 WHERE TABLE_SCHEMA = SCHEMA_NAME() 
                 AND TABLE_NAME = '{$TableName}'))
BEGIN
	CREATE TABLE {$TableName}(
		Id INT IDENTITY(1,1) NOT NULL,
		CollectionName NVARCHAR(128) NOT NULL,
		[Date] DATETIME2(7) NOT NULL,
		CONSTRAINT PK_{$TableName} PRIMARY KEY CLUSTERED (Id ASC))
	CREATE UNIQUE INDEX IX_{$TableName} ON {$TableName} (CollectionName ASC)
END
