// <auto-generated />
using System;
using ImagineCommunications.GamePlan.Persistence.SqlServer.Migrations.DbContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ImagineCommunications.GamePlan.Persistence.SqlServer.Migrations.IntelligenceMigrations
{
    [DbContext(typeof(IntelligenceMigrationDbContext))]
    [Migration("20200225135606_InitialIntelligenceMigration")]
    partial class InitialIntelligenceMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ImagineCommunications.Gameplan.Integration.Data.Entities.GroupTransactionInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("EventCount");

                    b.Property<DateTime?>("ExecutedDate");

                    b.Property<DateTime>("ReceivedDate");

                    b.Property<int>("RetryCount");

                    b.Property<int>("State");

                    b.HasKey("Id");

                    b.ToTable("GroupTransactionInfos");
                });

            modelBuilder.Entity("ImagineCommunications.Gameplan.Integration.Data.Entities.MessageInfo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime?>("ExecutedDate");

                    b.Property<Guid>("GroupTransactionId");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100);

                    b.Property<int>("Priority");

                    b.Property<DateTime>("ReceivedDate");

                    b.Property<int>("RetryCount");

                    b.Property<int>("State");

                    b.Property<int>("Type");

                    b.HasKey("Id");

                    b.ToTable("MessageInfos");
                });

            modelBuilder.Entity("ImagineCommunications.Gameplan.Integration.Data.Entities.MessagePayload", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<byte[]>("Payload")
                        .IsRequired()
                        .HasColumnType("VARBINARY(MAX)");

                    b.HasKey("Id");

                    b.ToTable("MessagePayloads");
                });

            modelBuilder.Entity("ImagineCommunications.Gameplan.Integration.Data.Entities.MessagePriority", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100);

                    b.Property<int>("Priority");

                    b.HasKey("Id");

                    b.ToTable("MessagePriorities");
                });

            modelBuilder.Entity("ImagineCommunications.Gameplan.Integration.Data.Entities.MessagePayload", b =>
                {
                    b.HasOne("ImagineCommunications.Gameplan.Integration.Data.Entities.MessageInfo")
                        .WithOne()
                        .HasForeignKey("ImagineCommunications.Gameplan.Integration.Data.Entities.MessagePayload", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
